openapi: 3.0.3
info:
  version: 1.0.0
  title: Request Service
  description: API for managing requests.
servers:
  - url: 'http:/localhost:8080/api'
paths:
  /request/contact/all:
    get:
      tags:
        - Contact Request
      summary: Getting all contact requests
      operationId: getAllContactRequests
      responses:
        "201":
          description: Successful retrieval of all contact requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContactRequestDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /request/contact/{id}:
    get:
      tags:
        - Contact Request
      summary: Getting single contact request by id
      operationId: getContactRequestById
      responses:
        "201":
          description: Successful retrieval of contact request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactRequestDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: query
          name: Request
          required: true
          description: The request id
  /request/contact/create:
    post:
      tags:
        - Contact Request
      summary: Create contact request
      operationId: createContactRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateContactRequestDTO"
      responses:
        "201":
          description: Successful creation of contact request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactRequestDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"

  /request/application/all:
    get:
      tags:
        - Application Request
      summary: Getting all application requests
      operationId: getAllApplicationRequests
      responses:
        "201":
          description: Successful retrieval of all application requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApplicationRequestDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /request/application/{id}:
    get:
      tags:
        - Application Request
      summary: Getting single application request by id
      operationId: getApplicationRequestById
      responses:
        "201":
          description: Successful retrieval of application request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationRequestDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: query
          name: Request
          required: true
          description: The request id
  /request/application/create:
    post:
      tags:
        - Application Request
      summary: Create application request
      operationId: createApplicationRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateApplicationRequestDTO"
      responses:
        "201":
          description: Successful creation of application request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationRequestDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"

components:
  schemas:
    ErrorDto:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ContactRequestDTO:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        isConsent:
          type: boolean
        subject:
          type: string
        message:
          type: string
        isApplicationRequest:
          type: boolean
        timeCreated:
          type: string
    CreateContactRequestDTO:
      type: object
      properties:
        email:
          type: string
        isConsent:
          type: boolean
        subject:
          type: string
        message:
          type: string
        isApplicationRequest:
          type: boolean
        timeCreated:
          type: string
    ApplicationRequestDTO:
      type: object
      properties:
        id:
          type: integer
        contactRequestId:
          type: integer
        playerName:
          type: string
        profileUrl:
          type: string
        maxRank:
          type: string
        birthday:
          type: string
        countryOrigin:
          type: string
        appliedGame:
          type: string
        appliedRole:
          type: string
        description:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - OTHER
    CreateApplicationRequestDTO:
      type: object
      properties:
        contactRequestId:
          type: integer
        playerName:
          type: string
        profileUrl:
          type: string
        maxRank:
          type: string
        birthday:
          type: string
        countryOrigin:
          type: string
        appliedGame:
          type: string
        appliedRole:
          type: string
        description:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - OTHER