springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8081

spring:
  cloud:
    compatibility-verifier:
      enabled: false
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

logging:
  level:
    root: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
