openapi: 3.0.3
info:
  version: 1.0.0
  title: Event Service
  description: API for managing events.
servers:
  - url: 'http:/localhost:8084/api'
paths:
  /event/all:
    get:
      tags:
        - Event
      summary: Getting all events
      operationId: getAllEvents
      responses:
        "201":
          description: Successful retrieval of all events.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /event/all/active:
    get:
      tags:
        - Event
      summary: Getting all active events
      operationId: getAllActiveEvents
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
      responses:
        "201":
          description: Successful retrieval of all events.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /event/{id}:
    get:
      tags:
        - Event
      summary: Getting single event by id
      operationId: getEventById
      responses:
        "201":
          description: Successful retrieval of event.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: Event
          required: true
          description: The event id
  /event/{id}/delete:
    get:
      tags:
        - Event
      summary: Deleting single event by id
      operationId: deleteEvent
      responses:
        "201":
          description: Successful deletion of event.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: Event
          required: true
          description: The event id
  /event/update:
    post:
      tags:
        - Event
      summary: Update event
      operationId: updateEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEventDTO"
      responses:
        "201":
          description: Successful update of event.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /event/create:
    post:
      tags:
        - Event
      summary: Create event
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEventDTO"
      responses:
        "201":
          description: Successful creation of event.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /event/all/date:
    post:
      tags:
        - Event
      summary: Getting all active events on date
      operationId: getAllEventsByDate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventDateDTO"
      responses:
        "201":
          description: Successful retrieval of all active events on date.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"

  /result/create:
    post:
      tags:
        - Result
      summary: Create result
      operationId: createResult
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatedResultDTO"
      responses:
        "201":
          description: Successful creation of event.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /result/all/active:
    get:
      tags:
        - Result
      summary: Getting all active results
      operationId: getAllActiveEvents
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
      responses:
        "201":
          description: Successful retrieval of all results.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResultDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
components:
  schemas:
    ErrorDto:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    EventDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        game:
          type: string
          format: uuid
        date:
          type: string
        info:
          type: string
        isActive:
          type: boolean
        enemyLogo:
          type: string
    ResultDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        dateTime:
          type: string
        game:
          type: string
          format: uuid
        enemyLogoURL:
          type: string
        enemyResult:
          type: string
        teamResult:
          type: string
        replayURL:
          type: string
        description:
          type: string
        isActive:
          type: boolean
    UpdateEventDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          required: true
        date:
          type: string
          required: false
        info:
          type: string
          required: false
        name:
          type: string
          required: false
        game:
          type: string
          format: uuid
          required: false
        enemyLogo:
          type: string
          required: false
    CreateEventDTO:
      type: object
      properties:
        date:
          type: string
          required: true
        info:
          type: string
          required: true
        name:
          type: string
          required: true
        game:
          type: string
          format: uuid
          required: true
        enemyLogo:
          type: string
          required: true
    CreatedResultDTO:
      type: object
      properties:
        eventId:
          type: string
          format: UUID
          required: true
        enemyResult:
          type: string
          required: true
        teamResult:
          type: string
          required: true
        replayURL:
          type: string
          required: true
    EventDateDTO:
      type: object
      properties:
        dateFrom:
          type: string
          required: false
        dateTo:
          type: string
          required: false
