spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vzk_roles
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    open-in-view: false
    database: mysql
    show-sql: true

  liquibase:
    enabled: false
    change-log: changelog/changelog-master.xml
    default-schema: vzk_roles

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8083

logging:
  level:
    root: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

