openapi: 3.0.3
info:
  version: 1.0.0
  title: Roles Service
  description: API for managing roles and permissions.
paths:
  /roles/all:
    get:
      tags:
        - Roles
      summary: Getting all roles
      operationId: getAllRoles
      responses:
        "200":
          description: Successful retrieval of all roles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /roles/all/active:
    get:
      tags:
        - Roles
      summary: Getting all active roles
      operationId: getAllActiveRoles
      responses:
        "200":
          description: Successful retrieval of all roles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /role/{id}:
    get:
      tags:
        - Roles
      summary: Getting single role by id
      operationId: getRoleById
      responses:
        "200":
          description: Successful retrieval of role.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: roleId
          required: true
          description: The id
  /role/create:
    post:
      tags:
        - Roles
      summary: Create role
      operationId: createRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: Successful creation of role.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /role/{id}/delete:
    get:
      tags:
        - Roles
      summary: Deleting single role by id
      operationId: deleteRole
      responses:
        "200":
          description: Successful deletion of role.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: Article
          required: true
          description: The article id
  /role/{id}/permissions:
    get:
      tags:
        - Roles
      summary: Getting permissions by id
      operationId: getPermissionsByRoleId
      responses:
        "200":
          description: Successful retrieval of all roles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PermissionDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: roleId
          required: true
          description: The id
  /role/{roleId}/addPermission/{permId}:
    post:
      tags:
        - Roles
      summary: Give account role
      operationId: giveRolePermission
      responses:
        "200":
          description: Successful.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: roleId
          required: true
          description: roleId
        - schema:
            type: string
            format: uuid
          in: query
          name: permId
          required: true
          description: permissionId
  /role/{id}/deletePermission:
    get:
      tags:
        - Roles
      summary: Delete permission role
      operationId: deletePermissionToRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              format: uuid
      responses:
        "200":
          description: Successful.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: roleId
          required: true
          description: roleId

  /permission/all:
    get:
      tags:
        - Permissions
      summary: Getting all permissions
      operationId: getAllPermissions
      responses:
        "200":
          description: Successful retrieval of all permissions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PermissionDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /permission/all/active:
    get:
      tags:
        - Permissions
      summary: Getting all active permissions
      operationId: getAllActivePermissions
      responses:
        "200":
          description: Successful retrieval of all active permissions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PermissionDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /permission/{id}:
    get:
      tags:
        - Permissions
      summary: Getting single permission by id
      operationId: getPermissionById
      responses:
        "200":
          description: Successful retrieval of permission.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: permissionId
          required: true
          description: The id
  /permission/create:
    post:
      tags:
        - Permissions
      summary: Create permission
      operationId: createPermission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: Successful creation of permission.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /permission/{id}/delete:
    get:
      tags:
        - Permissions
      summary: Deleting single permission by id
      operationId: deletePermission
      responses:
        "200":
          description: Successful deletion of permission.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: Permission
          required: true
          description: The permission id

  /role/account/{id}:
    get:
      tags:
        - Account
      summary: Getting roles of an account
      operationId: getRolesByAccountId
      responses:
        "200":
          description: Successful retrieval of roles of account.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleDTO'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: accountId
          required: true
          description: The id
  /role/account/{acc_id}/role/{role_id}:
    get:
      tags:
        - Account
      summary: Give account role
      operationId: giveAccountRole
      responses:
        "200":
          description: Successful.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: acc_id
          required: true
          description: acc_id
        - schema:
            type: string
            format: uuid
          in: query
          name: role_id
          required: true
          description: role_id
  /role/account/{acc_id}/delete/{role_id}:
    get:
      tags:
        - Account
      summary: Delete account role
      operationId: deleteAccountRole
      responses:
        "200":
          description: Successful.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: acc_id
          required: true
          description: acc_id
        - schema:
            type: string
            format: uuid
          in: query
          name: role_id
          required: true
          description: role_id
components:
  schemas:
    ErrorDto:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    RoleDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        isActive:
          type: boolean
    PermissionDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        isActive:
          type: boolean