openapi: 3.0.3
info:
  title: Authentication API
  version: 1.0.0
  description: API for user authentication
paths:
  /auth/login:
    post:
      summary: Authenticate a user
      tags:
        - authentication
      requestBody:
        description: User credentials for authentication
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialsDTO"
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT access token
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
components:
  schemas:
    ErrorDto:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    AccountDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
        username:
          type: string
        password:
          type: string
        isActive:
          type: boolean
    CredentialsDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string